# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'application.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(610, 467)
        Form.setMinimumSize(QtCore.QSize(600, 400))
        Form.setStyleSheet("background-color:white;\n"
"color:rgb(128,128,128);")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("QTabBar::tab{background-color:rgb(255,246,234);color:rgb(128,128,128);font:13px}\n"
"QTabBar::tab::selected{background-color:rgb(249,179,132);color:white;}\n"
"QTabWidget::pane{border: -1px;top:-2px;left: 1px;}\n"
"")
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.application_tabWidget = QtWidgets.QTabWidget(self.frame)
        self.application_tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.application_tabWidget.setFont(font)
        self.application_tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.application_tabWidget.setStyleSheet("QWidget{background-color:white; border:3px dotted rgb(249,179,132);}\n"
"QFrame{background-color:rgb(255,246,234)}\n"
"QHBoxLayout{background-color:rgb(255,246,234);}\n"
"QComboBox{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);background: rgb(249,179,132,30%);font:13px;color:grey;height: 20px;}\n"
"QComboBox:editable{background:rgb(249,179,132);}\n"
"QComboBox QAbstractItemView{border: 0px solid white;outline:0px;selection-background-color: white;height:100px;background: white;font:13px;color:white;}\n"
"QComboBox QAbstractItemView::item{height:50px;width:200px;} \n"
"QComboBox::down-arrow{border-image: url(:/icons/icon_downarrow.png);}\n"
"QComboBox::drop-down{border:0px;}\n"
"QComboBox::hover{border: 1px solid #C0C4CC;}\n"
"QLineEdit{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;}\n"
"QLineEdit::hover{border: 1px solid #C0C4CC;}\n"
"QTextEdit{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;}\n"
"QTextEdit::hover{border: 1px solid #C0C4CC;}")
        self.application_tabWidget.setObjectName("application_tabWidget")
        self.att_widget = QtWidgets.QWidget()
        self.att_widget.setStyleSheet("QWidget{background-color:white; border:none;}")
        self.att_widget.setObjectName("att_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.att_widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.att_widget)
        self.frame_3.setStyleSheet("QFrame{Border-style:none;background-color:rgb(255,246,234)}\n"
"QHBoxLayout{background-color:rgb(255,246,234);}")
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_3)
        self.dateEdit.setStyleSheet("QDateEdit::down-arrow {border-image: url(:/icons/riliriqi.png); }\n"
"QDateEdit::drop-down{width: 15px;background-color:rgb(255,246,234,60%)}\n"
"\n"
"QDateEdit{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);\n"
"}\n"
"QDateEdit::hover{border: 1px solid #C0C4CC;}\n"
"\n"
"QCalendarWidget QTableView  {alternate-background-color: rgb(251,212,185,60%) ;background-color:white;}\n"
"\n"
" QCalendarWidget::QWidget#qt_calendar_navigationbar{background-color: #2F2F3E;}\n"
"QTableView{selection-background-color:rgb(251,212,185,15%);selection-color: black;}\n"
"QComboBox{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);background: rgb(249,179,132,30%);font:13px;color:grey;height: 20px;}\n"
"QToolButton{background-color: transparent;margin:5px;border-style:none;color:rgb(128,128,128);font:13px;}\n"
"\n"
"\n"
"QToolButton#qt_calendar_monthbutton,#qt_calendar_yearbutton{\n"
"color: black; \n"
"}\n"
"QToolButton#qt_calendar_monthbutton{\n"
"width:70px;\n"
"\n"
"}\n"
"QToolButton#qt_calendar_monthbutton::QObject{\n"
"color: white; \n"
"}\n"
"QToolButton#qt_calendar_prevmonth{\n"
"qproperty-icon:url(:/icons/arrow-left-filling.png);\n"
"}\n"
"QToolButton#qt_calendar_nextmonth{\n"
"qproperty-icon:url(:/icons/arrow-right-filling.png)\n"
"}")
        self.dateEdit.setWrapping(False)
        self.dateEdit.setFrame(True)
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setKeyboardTracking(True)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_5.addWidget(self.dateEdit)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setStyleSheet("QComboBox{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);background: rgb(249,179,132,30%);font:13px;color:grey;height: 20px;}\n"
"QComboBox:editable{background:rgb(249,179,132);}\n"
"QComboBox QAbstractItemView{border: 0px solid rgb(255,246,234);outline:0px;selection-background-color: rgb(255,246,234);height:100px;background: rgb(255,246,234);font:13px;}\n"
"QComboBox QAbstractItemView::item{height:50px;width:200px;} \n"
"\n"
"QComboBox::down-arrow{border-image: url(:/icons/icon_downarrow.png);}\n"
"QComboBox::drop-down{border:0px;}\n"
"\n"
"\n"
"QComboBox::hover{border: 1px solid #C0C4CC;}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.status_comboBox = QtWidgets.QComboBox(self.frame_3)
        self.status_comboBox.setStyleSheet("QComboBox{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);background: rgb(249,179,132,30%);font:13px;color:grey;height: 20px;}\n"
"QComboBox:editable{background:rgb(249,179,132);}\n"
"QComboBox QAbstractItemView{border: 0px solid rgb(255,246,234);outline:0px;selection-background-color: rgb(255,246,234);height:100px;background: rgb(255,246,234);font:13px;}\n"
"QComboBox QAbstractItemView::item{height:50px;width:200px;} \n"
"\n"
"QComboBox::down-arrow{border-image: url(:/icons/icon_downarrow.png);}\n"
"QComboBox::drop-down{border:0px;}\n"
"\n"
"\n"
"QComboBox::hover{border: 1px solid #C0C4CC;}")
        self.status_comboBox.setObjectName("status_comboBox")
        self.status_comboBox.addItem("")
        self.status_comboBox.addItem("")
        self.status_comboBox.addItem("")
        self.status_comboBox.addItem("")
        self.status_comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.status_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.comment_textEdit = QtWidgets.QTextEdit(self.frame_3)
        self.comment_textEdit.setStyleSheet("background-color:rgb(249,179,132,30%)")
        self.comment_textEdit.setObjectName("comment_textEdit")
        self.horizontalLayout_8.addWidget(self.comment_textEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 4)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 3)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.application_tabWidget.addTab(self.att_widget, "")
        self.company_tab_2 = QtWidgets.QWidget()
        self.company_tab_2.setStyleSheet("QWidget{background-color:white; border:none;}")
        self.company_tab_2.setObjectName("company_tab_2")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.company_tab_2)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.frame_4 = QtWidgets.QFrame(self.company_tab_2)
        self.frame_4.setStyleSheet("QFrame{Border-style:none;background-color:rgb(255,246,234)}\n"
"QHBoxLayout{background-color:rgb(255,246,234);}")
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.type_comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.type_comboBox_2.setStyleSheet("QComboBox{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);background: rgb(249,179,132,30%);font:13px;color:grey;height: 20px;}\n"
"QComboBox:editable{background:rgb(249,179,132);}\n"
"QComboBox QAbstractItemView{border: 0px solid rgb(255,246,234);outline:0px;selection-background-color: rgb(255,246,234);height:100px;background: rgb(255,246,234);font:13px;}\n"
"QComboBox QAbstractItemView::item{height:50px;width:200px;} \n"
"\n"
"QComboBox::down-arrow{border-image: url(:/icons/icon_downarrow.png);}\n"
"QComboBox::drop-down{border:0px;}\n"
"\n"
"\n"
"QComboBox::hover{border: 1px solid #C0C4CC;}")
        self.type_comboBox_2.setObjectName("type_comboBox_2")
        self.horizontalLayout.addWidget(self.type_comboBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.company_lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.company_lineEdit.setStyleSheet("background-color:rgb(249,179,132,30%)")
        self.company_lineEdit.setText("")
        self.company_lineEdit.setObjectName("company_lineEdit")
        self.horizontalLayout_4.addWidget(self.company_lineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.comment_textEdit_2 = QtWidgets.QTextEdit(self.frame_4)
        self.comment_textEdit_2.setStyleSheet("background-color:rgb(249,179,132,30%)")
        self.comment_textEdit_2.setObjectName("comment_textEdit_2")
        self.horizontalLayout_11.addWidget(self.comment_textEdit_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 3)
        self.horizontalLayout_11.setStretch(2, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_27.addWidget(self.frame_4)
        self.application_tabWidget.addTab(self.company_tab_2, "")
        self.vaca_tab_3 = QtWidgets.QWidget()
        self.vaca_tab_3.setStyleSheet("QWidget{background-color:white; border:none;}")
        self.vaca_tab_3.setObjectName("vaca_tab_3")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.vaca_tab_3)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frame_5 = QtWidgets.QFrame(self.vaca_tab_3)
        self.frame_5.setStyleSheet("QFrame{Border-style:none;background-color:rgb(255,246,234)}\n"
"QHBoxLayout{background-color:rgb(255,246,234);}")
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        self.start_dateEdit = QtWidgets.QDateEdit(self.frame_5)
        self.start_dateEdit.setStyleSheet("QDateEdit::down-arrow {border-image: url(:/icons/riliriqi.png); }\n"
"QDateEdit::drop-down{width: 15px;background-color:rgb(255,246,234,60%)}\n"
"\n"
"QDateEdit{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);\n"
"}\n"
"QDateEdit::hover{border: 1px solid #C0C4CC;}\n"
"\n"
"QCalendarWidget QTableView  {alternate-background-color: rgb(251,212,185,60%) ;background-color:white;}\n"
"\n"
" QCalendarWidget::QWidget#qt_calendar_navigationbar{background-color: #2F2F3E;}\n"
"QTableView{selection-background-color:rgb(251,212,185,15%);selection-color: black;}\n"
"QComboBox{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);background: rgb(249,179,132,30%);font:13px;color:grey;height: 20px;}\n"
"QToolButton{background-color: transparent;margin:5px;border-style:none;color:rgb(128,128,128);font:13px;}\n"
"\n"
"\n"
"QToolButton#qt_calendar_monthbutton,#qt_calendar_yearbutton{\n"
"color: black; \n"
"}\n"
"QToolButton#qt_calendar_monthbutton{\n"
"width:70px;\n"
"\n"
"}\n"
"QToolButton#qt_calendar_monthbutton::QObject{\n"
"color: white; \n"
"}\n"
"QToolButton#qt_calendar_prevmonth{\n"
"qproperty-icon:url(:/icons/arrow-left-filling.png);\n"
"}\n"
"QToolButton#qt_calendar_nextmonth{\n"
"qproperty-icon:url(:/icons/arrow-right-filling.png)\n"
"}")
        self.start_dateEdit.setProperty("showGroupSeparator", False)
        self.start_dateEdit.setCalendarPopup(True)
        self.start_dateEdit.setObjectName("start_dateEdit")
        self.horizontalLayout_14.addWidget(self.start_dateEdit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(2, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_15.addWidget(self.label_10)
        self.end_dateEdit = QtWidgets.QDateEdit(self.frame_5)
        self.end_dateEdit.setStyleSheet("QDateEdit::down-arrow {border-image: url(:/icons/riliriqi.png); }\n"
"QDateEdit::drop-down{width: 15px;background-color:rgb(255,246,234,60%)}\n"
"\n"
"QDateEdit{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);\n"
"}\n"
"QDateEdit::hover{border: 1px solid #C0C4CC;}\n"
"\n"
"QCalendarWidget QTableView  {alternate-background-color: rgb(251,212,185,60%) ;background-color:white;}\n"
"\n"
" QCalendarWidget::QWidget#qt_calendar_navigationbar{background-color: #2F2F3E;}\n"
"QTableView{selection-background-color:rgb(251,212,185,15%);selection-color: black;}\n"
"QComboBox{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);background: rgb(249,179,132,30%);font:13px;color:grey;height: 20px;}\n"
"QToolButton{background-color: transparent;margin:5px;border-style:none;color:rgb(128,128,128);font:13px;}\n"
"\n"
"\n"
"QToolButton#qt_calendar_monthbutton,#qt_calendar_yearbutton{\n"
"color: black; \n"
"}\n"
"QToolButton#qt_calendar_monthbutton{\n"
"width:70px;\n"
"\n"
"}\n"
"QToolButton#qt_calendar_monthbutton::QObject{\n"
"color: white; \n"
"}\n"
"QToolButton#qt_calendar_prevmonth{\n"
"qproperty-icon:url(:/icons/arrow-left-filling.png);\n"
"}\n"
"QToolButton#qt_calendar_nextmonth{\n"
"qproperty-icon:url(:/icons/arrow-right-filling.png)\n"
"}")
        self.end_dateEdit.setCalendarPopup(True)
        self.end_dateEdit.setObjectName("end_dateEdit")
        self.horizontalLayout_15.addWidget(self.end_dateEdit)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 1)
        self.horizontalLayout_15.setStretch(2, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_16.addWidget(self.label_8)
        self.comment_textEdit_3 = QtWidgets.QTextEdit(self.frame_5)
        self.comment_textEdit_3.setStyleSheet("background-color:rgb(249,179,132,30%)")
        self.comment_textEdit_3.setObjectName("comment_textEdit_3")
        self.horizontalLayout_16.addWidget(self.comment_textEdit_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 3)
        self.horizontalLayout_16.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 3)
        self.horizontalLayout_26.addWidget(self.frame_5)
        self.application_tabWidget.addTab(self.vaca_tab_3, "")
        self.back_tab_4 = QtWidgets.QWidget()
        self.back_tab_4.setStyleSheet("QWidget{background-color:white; border:none;}")
        self.back_tab_4.setObjectName("back_tab_4")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.back_tab_4)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.frame_2 = QtWidgets.QFrame(self.back_tab_4)
        self.frame_2.setStyleSheet("QFrame{Border-style:none;background-color:rgb(255,246,234)}\n"
"QHBoxLayout{background-color:rgb(255,246,234);}")
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.back_dateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.back_dateEdit.setStyleSheet("QDateEdit::down-arrow {border-image: url(:/icons/riliriqi.png); }\n"
"QDateEdit::drop-down{width: 15px;background-color:rgb(255,246,234,60%)}\n"
"\n"
"QDateEdit{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);\n"
"}\n"
"QDateEdit::hover{border: 1px solid #C0C4CC;}\n"
"\n"
"QCalendarWidget QTableView  {alternate-background-color: rgb(251,212,185,60%) ;background-color:white;}\n"
"\n"
" QCalendarWidget::QWidget#qt_calendar_navigationbar{background-color: #2F2F3E;}\n"
"QTableView{selection-background-color:rgb(251,212,185,15%);selection-color: black;}\n"
"QComboBox{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);background: rgb(249,179,132,30%);font:13px;color:grey;height: 20px;}\n"
"QToolButton{background-color: transparent;margin:5px;border-style:none;color:rgb(128,128,128);font:13px;}\n"
"\n"
"\n"
"QToolButton#qt_calendar_monthbutton,#qt_calendar_yearbutton{\n"
"color: black; \n"
"}\n"
"QToolButton#qt_calendar_monthbutton{\n"
"width:70px;\n"
"\n"
"}\n"
"QToolButton#qt_calendar_monthbutton::QObject{\n"
"color: white; \n"
"}\n"
"QToolButton#qt_calendar_prevmonth{\n"
"qproperty-icon:url(:/icons/arrow-left-filling.png);\n"
"}\n"
"QToolButton#qt_calendar_nextmonth{\n"
"qproperty-icon:url(:/icons/arrow-right-filling.png)\n"
"}")
        self.back_dateEdit.setCalendarPopup(True)
        self.back_dateEdit.setObjectName("back_dateEdit")
        self.horizontalLayout_2.addWidget(self.back_dateEdit)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comment_textEdit_4 = QtWidgets.QTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment_textEdit_4.sizePolicy().hasHeightForWidth())
        self.comment_textEdit_4.setSizePolicy(sizePolicy)
        self.comment_textEdit_4.setStyleSheet("background-color:rgb(249,179,132,30%)")
        self.comment_textEdit_4.setObjectName("comment_textEdit_4")
        self.horizontalLayout_3.addWidget(self.comment_textEdit_4)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.horizontalLayout_25.addWidget(self.frame_2)
        self.application_tabWidget.addTab(self.back_tab_4, "")
        self.out_tab_5 = QtWidgets.QWidget()
        self.out_tab_5.setStyleSheet("QWidget{background-color:white; border:none;}")
        self.out_tab_5.setObjectName("out_tab_5")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.out_tab_5)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_6 = QtWidgets.QFrame(self.out_tab_5)
        self.frame_6.setStyleSheet("QFrame{Border-style:none;background-color:rgb(255,246,234)}\n"
"QHBoxLayout{background-color:rgb(255,246,234);}")
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        self.outs_dateEdit = QtWidgets.QDateEdit(self.frame_6)
        self.outs_dateEdit.setStyleSheet("QDateEdit::down-arrow {border-image: url(:/icons/riliriqi.png); }\n"
"QDateEdit::drop-down{width: 15px;background-color:rgb(255,246,234,60%)}\n"
"\n"
"QDateEdit{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);\n"
"}\n"
"QDateEdit::hover{border: 1px solid #C0C4CC;}\n"
"\n"
"QCalendarWidget QTableView  {alternate-background-color: rgb(251,212,185,60%) ;background-color:white;}\n"
"\n"
" QCalendarWidget::QWidget#qt_calendar_navigationbar{background-color: #2F2F3E;}\n"
"QTableView{selection-background-color:rgb(251,212,185,15%);selection-color: black;}\n"
"QComboBox{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);background: rgb(249,179,132,30%);font:13px;color:grey;height: 20px;}\n"
"QToolButton{background-color: transparent;margin:5px;border-style:none;color:rgb(128,128,128);font:13px;}\n"
"\n"
"\n"
"QToolButton#qt_calendar_monthbutton,#qt_calendar_yearbutton{\n"
"color: black; \n"
"}\n"
"QToolButton#qt_calendar_monthbutton{\n"
"width:70px;\n"
"\n"
"}\n"
"QToolButton#qt_calendar_monthbutton::QObject{\n"
"color: white; \n"
"}\n"
"QToolButton#qt_calendar_prevmonth{\n"
"qproperty-icon:url(:/icons/arrow-left-filling.png);\n"
"}\n"
"QToolButton#qt_calendar_nextmonth{\n"
"qproperty-icon:url(:/icons/arrow-right-filling.png)\n"
"}")
        self.outs_dateEdit.setCalendarPopup(True)
        self.outs_dateEdit.setObjectName("outs_dateEdit")
        self.horizontalLayout_18.addWidget(self.outs_dateEdit)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem11)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 1)
        self.horizontalLayout_18.setStretch(2, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_19.addWidget(self.label_11)
        self.oute_dateEdit = QtWidgets.QDateEdit(self.frame_6)
        self.oute_dateEdit.setStyleSheet("QDateEdit::down-arrow {border-image: url(:/icons/riliriqi.png); }\n"
"QDateEdit::drop-down{width: 15px;background-color:rgb(255,246,234,60%)}\n"
"\n"
"QDateEdit{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);\n"
"}\n"
"QDateEdit::hover{border: 1px solid #C0C4CC;}\n"
"\n"
"QCalendarWidget QTableView  {alternate-background-color: rgb(251,212,185,60%) ;background-color:white;}\n"
"\n"
" QCalendarWidget::QWidget#qt_calendar_navigationbar{background-color: #2F2F3E;}\n"
"QTableView{selection-background-color:rgb(251,212,185,15%);selection-color: black;}\n"
"QComboBox{border: 1px solid rgb(249,179,132,30%);border-radius: 3px;background-color:rgb(249,179,132,30%);background: rgb(249,179,132,30%);font:13px;color:grey;height: 20px;}\n"
"QToolButton{background-color: transparent;margin:5px;border-style:none;color:rgb(128,128,128);font:13px;}\n"
"\n"
"\n"
"QToolButton#qt_calendar_monthbutton,#qt_calendar_yearbutton{\n"
"color: black; \n"
"}\n"
"QToolButton#qt_calendar_monthbutton{\n"
"width:70px;\n"
"\n"
"}\n"
"QToolButton#qt_calendar_monthbutton::QObject{\n"
"color: white; \n"
"}\n"
"QToolButton#qt_calendar_prevmonth{\n"
"qproperty-icon:url(:/icons/arrow-left-filling.png);\n"
"}\n"
"QToolButton#qt_calendar_nextmonth{\n"
"qproperty-icon:url(:/icons/arrow-right-filling.png)\n"
"}")
        self.oute_dateEdit.setCalendarPopup(True)
        self.oute_dateEdit.setObjectName("oute_dateEdit")
        self.horizontalLayout_19.addWidget(self.oute_dateEdit)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem12)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 1)
        self.horizontalLayout_19.setStretch(2, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_20.addWidget(self.label_13)
        self.place_lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.place_lineEdit.setStyleSheet("background-color:rgb(249,179,132,30%);\n"
"padding:0px 2px")
        self.place_lineEdit.setObjectName("place_lineEdit")
        self.horizontalLayout_20.addWidget(self.place_lineEdit)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem13)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 1)
        self.horizontalLayout_20.setStretch(2, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_21.addWidget(self.label_5)
        self.comment_textEdit_5 = QtWidgets.QTextEdit(self.frame_6)
        self.comment_textEdit_5.setStyleSheet("background-color:rgb(249,179,132,30%)")
        self.comment_textEdit_5.setObjectName("comment_textEdit_5")
        self.horizontalLayout_21.addWidget(self.comment_textEdit_5)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem14)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 3)
        self.horizontalLayout_21.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 3)
        self.horizontalLayout_24.addWidget(self.frame_6)
        self.application_tabWidget.addTab(self.out_tab_5, "")
        self.verticalLayout_6.addWidget(self.application_tabWidget)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.submitButton = QtWidgets.QPushButton(self.frame)
        self.submitButton.setStyleSheet("\n"
"background-color:rgb(255,183,134);\n"
"color:white;\n"
"border:6px;\n"
"border-radius:10px;\n"
"padding:4px 10px;")
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout_9.addWidget(self.submitButton)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.horizontalLayout_9.setStretch(0, 3)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6.addWidget(self.frame)

        self.retranslateUi(Form)
        self.application_tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "异常时间："))
        self.dateEdit.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.comboBox.setItemText(0, _translate("Form", "上班"))
        self.comboBox.setItemText(1, _translate("Form", "下班"))
        self.label_16.setText(_translate("Form", "修改状态："))
        self.status_comboBox.setItemText(0, _translate("Form", "出勤"))
        self.status_comboBox.setItemText(1, _translate("Form", "迟到"))
        self.status_comboBox.setItemText(2, _translate("Form", "早退"))
        self.status_comboBox.setItemText(3, _translate("Form", "缺勤"))
        self.status_comboBox.setItemText(4, _translate("Form", "请假"))
        self.label_3.setText(_translate("Form", "申请原因："))
        self.application_tabWidget.setTabText(self.application_tabWidget.indexOf(self.att_widget), _translate("Form", "考勤申诉"))
        self.label_15.setText(_translate("Form", "变动："))
        self.label_6.setText(_translate("Form", "公司："))
        self.label_7.setText(_translate("Form", "备注："))
        self.application_tabWidget.setTabText(self.application_tabWidget.indexOf(self.company_tab_2), _translate("Form", "职位变动"))
        self.label_9.setText(_translate("Form", "开始日期："))
        self.start_dateEdit.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.label_10.setText(_translate("Form", "结束日期："))
        self.end_dateEdit.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.label_8.setText(_translate("Form", "请假缘由："))
        self.application_tabWidget.setTabText(self.application_tabWidget.indexOf(self.vaca_tab_3), _translate("Form", "请假申请"))
        self.label_2.setText(_translate("Form", "销假日期："))
        self.back_dateEdit.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.label_4.setText(_translate("Form", "销假备注："))
        self.application_tabWidget.setTabText(self.application_tabWidget.indexOf(self.back_tab_4), _translate("Form", "销假申请"))
        self.label_12.setText(_translate("Form", "开始日期："))
        self.outs_dateEdit.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.label_11.setText(_translate("Form", "结束日期："))
        self.oute_dateEdit.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.label_13.setText(_translate("Form", "外派地点："))
        self.label_5.setText(_translate("Form", "外派缘由："))
        self.application_tabWidget.setTabText(self.application_tabWidget.indexOf(self.out_tab_5), _translate("Form", "外派申请"))
        self.submitButton.setText(_translate("Form", "提交"))
import icons_rc
