# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changepwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_changepwdForm(object):
    def setupUi(self, changepwdForm):
        changepwdForm.setObjectName("changepwdForm")
        changepwdForm.resize(500, 300)
        changepwdForm.setStyleSheet("background-color:white;color:rgb(128,128,128);")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(changepwdForm)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(changepwdForm)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setStyleSheet("border-style:none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.oldpwdEdit = QtWidgets.QLineEdit(self.frame_6)
        self.oldpwdEdit.setStyleSheet("font-size:20px;\n"
"border-style:solid ;\n"
"border-width:1px;\n"
"border-color:rgb(218, 218, 218);\n"
"border-radius:10px;\n"
"padding:1px,1px")
        self.oldpwdEdit.setObjectName("oldpwdEdit")
        self.horizontalLayout_5.addWidget(self.oldpwdEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_5.setStretch(1, 2)
        self.horizontalLayout_5.setStretch(2, 5)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("border-style:none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.newpwdEdit = QtWidgets.QLineEdit(self.frame_4)
        self.newpwdEdit.setStyleSheet("font-size:20px;\n"
"border-style:solid ;\n"
"border-width:1px;\n"
"border-color:rgb(218, 218, 218);\n"
"border-radius:10px;\n"
"padding:1px,1px")
        self.newpwdEdit.setObjectName("newpwdEdit")
        self.horizontalLayout_2.addWidget(self.newpwdEdit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 5)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("border-style:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.newpwdEdit2 = QtWidgets.QLineEdit(self.frame_5)
        self.newpwdEdit2.setStyleSheet("font-size:20px;\n"
"border-style:solid ;\n"
"border-width:1px;\n"
"border-color:rgb(218, 218, 218);\n"
"border-radius:10px;\n"
"padding:1px,1px")
        self.newpwdEdit2.setObjectName("newpwdEdit2")
        self.horizontalLayout_4.addWidget(self.newpwdEdit2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 5)
        self.verticalLayout.addWidget(self.frame_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("border-style:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.bt_changepwd = QtWidgets.QPushButton(self.frame_2)
        self.bt_changepwd.setStyleSheet("font-size:20px;\n"
"border-style:solid ;\n"
"border-width:1px;\n"
"border-radius:10px;\n"
"padding:1px,1px;\n"
"background-color:rgb(255,183,134);\n"
"color:white;\n"
"border:6px;\n"
"padding:4px 10px;")
        self.bt_changepwd.setObjectName("bt_changepwd")
        self.horizontalLayout.addWidget(self.bt_changepwd)
        spacerItem9 = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.bt_cancle = QtWidgets.QPushButton(self.frame_2)
        self.bt_cancle.setStyleSheet("font-size:20px;\n"
"border-style:solid ;\n"
"border-width:1px;\n"
"border-radius:10px;\n"
"padding:1px,1px;\n"
"background-color:rgb(255,183,134);\n"
"color:white;\n"
"border:6px;\n"
"padding:4px 10px;")
        self.bt_cancle.setObjectName("bt_cancle")
        self.horizontalLayout.addWidget(self.bt_cancle)
        spacerItem10 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 6)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 4)
        self.horizontalLayout_3.addWidget(self.frame_3)

        self.retranslateUi(changepwdForm)
        QtCore.QMetaObject.connectSlotsByName(changepwdForm)

    def retranslateUi(self, changepwdForm):
        _translate = QtCore.QCoreApplication.translate
        changepwdForm.setWindowTitle(_translate("changepwdForm", "修改密码"))
        self.label_3.setText(_translate("changepwdForm", "旧密码："))
        self.label.setText(_translate("changepwdForm", "新密码："))
        self.label_2.setText(_translate("changepwdForm", "确认新密码："))
        self.bt_changepwd.setText(_translate("changepwdForm", "确 认"))
        self.bt_cancle.setText(_translate("changepwdForm", "取 消"))
